whycon_ros:
  ros__parameters:
    # Whether to identify IDs
    identify : true
    #Marker's outer diameter [cm]
    circleDiameter : 0.012
    #Number of markers to track
    maxMarkers : 4
  
    #Distance of markers in x-axis in custom coordinate system
    fieldLength : 1.0
    #Distance of markers in y-axis in custom coordinate system
    fieldWidth : 1.0

    useGui: true
    idBits: 1
    idSamples: 1
    hammingDist: 1

